//! Shell completion generation.
//!
//! Mirrors jc's bash_completion / zsh_completion output.
//! Generates completion scripts for bash and zsh from the live parser registry.

use cj_core::registry::all_parsers;

/// Collect all parser argument names (e.g. "--df", "--ls") from registry.
fn parser_arguments() -> Vec<String> {
    let mut args: Vec<String> = all_parsers()
        .filter(|p| !p.info().hidden && !p.info().deprecated)
        .map(|p| p.info().argument.to_string())
        .collect();
    args.sort();
    args
}

/// Collect all magic commands from registry.
fn magic_commands() -> Vec<String> {
    let mut cmds: Vec<String> = all_parsers()
        .flat_map(|p| p.info().magic_commands.iter().map(|s| s.to_string()))
        .collect();
    cmds.sort();
    cmds.dedup();
    cmds
}

/// Generate bash completion script.
///
/// Usage: `cj --bash-comp > /etc/bash_completion.d/cj`
pub fn bash_completion() -> String {
    let parsers = parser_arguments();
    let magic = magic_commands();

    let parser_list = parsers.join(" ");
    let magic_list = magic.join(" ");

    // Standard cj options (mirrors jc)
    let options = concat!(
        "--about --force-color --debug --help --monochrome --meta-out ",
        "--pretty --quiet --raw --slurp --unbuffer --version --yaml-out ",
        "--bash-comp --zsh-comp --list --list-all"
    );

    format!(
        r#"# cj bash completion
# Generated by: cj --bash-comp

_cj_bash_complete()
{{
    local cur prev words cword
    _init_completion || return

    local parsers="{parser_list}"
    local magic_cmds="{magic_list}"
    local options="{options}"

    if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$parsers $options" -- "$cur") )
        return 0
    fi

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "-a -C -d -h -m -M -p -q -r -s -u -v -y -B -Z -l -L" -- "$cur") )
        return 0
    fi

    COMPREPLY=( $(compgen -W "$magic_cmds" -- "$cur") )
}}

complete -F _cj_bash_complete cj
"#,
        parser_list = parser_list,
        magic_list = magic_list,
        options = options,
    )
}

/// Generate zsh completion script.
///
/// Usage: `cj --zsh-comp > "${fpath[1]}/_cj"`
pub fn zsh_completion() -> String {
    let _parsers = parser_arguments();

    let parser_specs: Vec<String> = all_parsers()
        .filter(|p| !p.info().hidden && !p.info().deprecated)
        .map(|p| {
            // Escape special chars in description for zsh
            let desc = p
                .info()
                .description
                .replace('\'', "\\'")
                .replace(':', "\\:");
            format!("    '{}[{}]'", p.info().argument, desc)
        })
        .collect::<Vec<_>>();

    let parser_section = parser_specs.join(" \\\n");

    format!(
        r#"#compdef cj
# cj zsh completion
# Generated by: cj --zsh-comp

_cj() {{
    local context state state_descr line
    typeset -A opt_args

    _arguments -s \
        '(-a --about){{-a,--about}}[about cj]' \
        '(-C --force-color){{-C,--force-color}}[force color output]' \
        '(-d --debug){{-d,--debug}}[debug mode]' \
        '(-h --help){{-h,--help}}[show help]' \
        '(-m --monochrome){{-m,--monochrome}}[monochrome output]' \
        '(-M --meta-out){{-M,--meta-out}}[add metadata to output]' \
        '(-p --pretty){{-p,--pretty}}[pretty print output]' \
        '(-q --quiet){{-q,--quiet}}[suppress warnings]' \
        '(-r --raw){{-r,--raw}}[raw output]' \
        '(-s --slurp){{-s,--slurp}}[slurp multiple lines]' \
        '(-u --unbuffer){{-u,--unbuffer}}[unbuffer output]' \
        '(-v --version){{-v,--version}}[version info]' \
        '(-y --yaml-out){{-y,--yaml-out}}[YAML output]' \
        '(-B --bash-comp){{-B,--bash-comp}}[generate bash completion]' \
        '(-Z --zsh-comp){{-Z,--zsh-comp}}[generate zsh completion]' \
        '(-l --list){{-l,--list}}[list parsers]' \
        '(-L --list-all){{-L,--list-all}}[list all parsers including hidden]' \
{parser_section}
}}

_cj "$@"
"#,
        parser_section = parser_section,
    )
}

/// Generate fish completion script.
#[allow(dead_code)]
pub fn fish_completion() -> String {
    let _parsers = parser_arguments();

    let parser_completions: Vec<String> = all_parsers()
        .filter(|p| !p.info().hidden && !p.info().deprecated)
        .map(|p| {
            let arg = p.info().argument.trim_start_matches('-');
            let desc = p.info().description.replace('\'', "\\'");
            format!("complete -c cj -l '{}' -d '{}'", arg, desc)
        })
        .collect();

    let options = vec![
        ("a", "about", "about cj"),
        ("C", "force-color", "force color output"),
        ("d", "debug", "debug mode"),
        ("h", "help", "show help"),
        ("m", "monochrome", "monochrome output"),
        ("M", "meta-out", "add metadata to output"),
        ("p", "pretty", "pretty print output"),
        ("q", "quiet", "suppress warnings"),
        ("r", "raw", "raw output"),
        ("s", "slurp", "slurp multiple lines"),
        ("u", "unbuffer", "unbuffer output"),
        ("v", "version", "version info"),
        ("y", "yaml-out", "YAML output"),
        ("B", "bash-comp", "generate bash completion"),
        ("Z", "zsh-comp", "generate zsh completion"),
        ("l", "list", "list parsers"),
        ("L", "list-all", "list all parsers"),
    ];

    let option_completions: Vec<String> = options
        .iter()
        .map(|(short, long, desc)| {
            format!("complete -c cj -s '{}' -l '{}' -d '{}'", short, long, desc)
        })
        .collect();

    format!(
        "# cj fish completion\n# Generated by: cj --fish-comp\n\n{}\n\n{}\n",
        option_completions.join("\n"),
        parser_completions.join("\n"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── bash_completion ───────────────────────────────────────────────────────

    #[test]
    fn test_bash_completion_has_header_comment() {
        let script = bash_completion();
        assert!(script.starts_with("# cj bash completion"));
    }

    #[test]
    fn test_bash_completion_has_function_definition() {
        let script = bash_completion();
        assert!(script.contains("_cj_bash_complete"));
        assert!(script.contains("complete -F _cj_bash_complete cj"));
    }

    #[test]
    fn test_bash_completion_lists_known_long_options() {
        let script = bash_completion();
        assert!(script.contains("--pretty"));
        assert!(script.contains("--quiet"));
        assert!(script.contains("--raw"));
        assert!(script.contains("--version"));
    }

    #[test]
    fn test_bash_completion_lists_short_options() {
        let script = bash_completion();
        assert!(script.contains("-a "));
        assert!(script.contains("-p "));
    }

    #[test]
    fn test_bash_completion_is_nonempty() {
        let script = bash_completion();
        assert!(!script.is_empty());
    }

    // ── zsh_completion ────────────────────────────────────────────────────────

    #[test]
    fn test_zsh_completion_is_nonempty() {
        let script = zsh_completion();
        assert!(!script.is_empty());
    }

    #[test]
    fn test_zsh_completion_has_compdef_header() {
        let script = zsh_completion();
        assert!(script.contains("#compdef cj"));
    }

    #[test]
    fn test_zsh_completion_has_function_body() {
        let script = zsh_completion();
        assert!(script.contains("_cj()"));
        assert!(script.contains("_cj \"$@\""));
    }

    #[test]
    fn test_zsh_completion_has_option_flags() {
        let script = zsh_completion();
        assert!(script.contains("--pretty"));
        assert!(script.contains("--version"));
    }

    // ── fish_completion ───────────────────────────────────────────────────────

    #[test]
    fn test_fish_completion_has_header() {
        let script = fish_completion();
        assert!(script.contains("# cj fish completion"));
    }

    #[test]
    fn test_fish_completion_has_short_options() {
        let script = fish_completion();
        assert!(script.contains("complete -c cj -s 'p'"));
        assert!(script.contains("complete -c cj -s 'v'"));
    }
}
